version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=12345678
